### ISSUE TITLE
NONMEM and bbi versions in config_log

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/rbabylon#115]
# Summary

As a user I would like to have some additional fields extracted from `bbi_config.json` into the `config_log` output:

* bbi_version
* nonmem_version

# Tests

**Comment by seth127** [comment]
Combining implementation with https://github.com/metrumresearchgroup/rbabylon/issues/116

**Comment by copernican** [comment]
@seth127 is `nonmem_version` the value of `executable` for the case `default: true`? So if the JSON is the one used in the tests, i.e., 

```json
"nonmem": {
  "nm73gf": {
    "home": "/opt/NONMEM/nm73gf",
    "executable": "nmfe73",
    "nmqual": true
  },
  "nm73gf_nmfe": {
    "home": "/opt/NONMEM/nm73gf_nmfe",
    "executable": "nmfe73"
  },
  "nm74gf": {
    "home": "/opt/NONMEM/nm74gf",
    "executable": "nmfe74",
    "nmqual": true,
    "default": true
  },
  "nm74gf_nmfe": {
    "home": "/opt/NONMEM/nm74gf_nmfe",
    "executable": "nmfe74"
  }
}
```
then `nonmem_version` should be `nmfe74`?

**Comment by seth127** [comment]
I believe that's right, although we should ask @kylebaron because this was his ask originally. 

Kyle: is it sufficient to just take the value of relevant `executable` field from this json. So, in this case, we would return `nonmem_version: nmfe74`. Or should it be the key (which appears to be the basename of `"home"` so that in this case we would return `nm74gf`?

**Comment by seth127** [comment]
@copernican there is also another wrinkle that you should investigate. In most cases, you are correct that the version with `default: true` is the one that was used for the run. However, I know that you can pass an `nm_version` argument (through `.bbi_args`) as defined here https://github.com/metrumresearchgroup/rbabylon/blob/master/R/aaa.R#L17

I'm not sure, but my hunch is that, in the resulting `bbi_config.json` this would _not_ change the default value on any of these but would instead add another top-level field for `nm_version: ...`

Again, I'm not sure, but we should try that and see if that's right and, if so, the function should first check if that field exists and only parse the `default: true` from the array above when the top-level field is _not_ there. Crystal clear, right?

**Comment by copernican** [comment]
From some ad hoc testing, the NONMEM configuration used for the run appears to be represented in `bbi_config.json` as described below.

- If `nm_version` is not passed, then the configuration used is the one with `default: true`.

    ```json
    {
      "configuration": {
        "nonmem": {
          "nm74gf": {
            "executable": "nmfe74",
            "default": true
          }
        }
      }
    }
    ```

  In this case, `nm_version` is not recorded.

- If `nm_version` is passed, then the configuration used is recorded as `nm_version`, and it corresponds to one of the configurations in the `nonmem` block.

    ```json
    {
      "configuration": {
        "nm_version": "nm73gf_nmfe",
        "nonmem": {
          "nm73gf_nmfe": {
            "executable": "nmfe73"
          },
          "nm74gf": {
            "executable": "nmfe74",
            "default": true
          }
        }
      }
    }
    ```

    Of note, passing `nm_version` does not affect which configuration is the default (as you suspected).

From this behavior, it is straightforward to determine which configuration was used. We still need clarity on which of these fields should be extracted as the "version." For example, in the second case, we could use either `nm73gf_nmfe` or `nmfe73`.

**Comment by kylebaron** [comment]
With respect to nonmem version, we want to get something like `7.4.4`:

In the `root.lst` file:

```
1NONLINEAR MIXED EFFECTS MODEL PROGRAM (NONMEM) VERSION 7.4.4
 ORIGINALLY DEVELOPED BY STUART BEAL, LEWIS SHEINER, AND ALISON BOECKMANN
 CURRENT DEVELOPERS ARE ROBERT BAUER, ICON DEVELOPMENT SOLUTIONS,
 AND ALISON BOECKMANN. IMPLEMENTATION, EFFICIENCY, AND STANDARDIZATION
 PERFORMED BY NOUS INFOSYSTEMS.
```

In the `root.xml` file:

```r
library(xml2)
xml <- as_list(read_xml("../model/pk/999/999.xml"))
attributes(xml$output$nonmem)$version
```

or

```r
xml$output$nonmem$program_information
```

This currently returns:

```
7.4.4
```

I guess there should be a way to go back to the NONMEM install directory too.

**Comment by kylebaron** [comment]
EDIT: we currently only report something like `7.4` in the report template.  If this holds, we may only need the name of the executable.  I will check on this and get back as this might be really easy to get.

**Comment by kylebaron** [comment]
Regarding nonmem version:

If all we can get is something like `nmfe74` then the executable name is fine.  That should say that that you are using NONMEM 7.4.x

For our reporting, we can get the minor version with:

```r
x <- 
  read_model("106.yaml", .d = "../model/pk/") %>% 
  model_summary()
  
x$run_details$version
```
And the latter should be authoritative since it is coming form a model that was actually run through nonmem.   So either of those should work depending on what level of detail you're looking for.

**Comment by seth127** [comment]
Per this comment, the plan is to close #116 because the information captured in this issue is sufficient.
https://github.com/metrumresearchgroup/rbabylon/issues/116#issuecomment-685994716

@kylebaron two questions:

* is it sufficient to capture the key from the array above? As in (in this case) one of `["nm73gf", "nm73gf_nmfe", "nm74gf", "nm74gf_nmfe"]`?
* if so, is there strong enough naming convention in those\* that we could parse the major.minor version number and maybe even the compiler (`gf` = G Fortran right? We could just have a simple mapping).

\* i.e. are they named by NONMEM and will always have a consistent pattern or are they named by whoever installs them?

**Comment by seth127** [comment]
Oh wait, I realized I missed this comment above https://github.com/metrumresearchgroup/rbabylon/issues/115#issuecomment-685987529

If that still holds then let's ignore my comment from 15 mins ago and just extract the executable (one of `["nmfe73", "nmfe74"]` in this case). @kylebaron can you confirm that's the final decision?

**Comment by seth127** [comment]
Ok @copernican @kylebaron and I just talked on zoom. Decision:

Add a column called `nm_version` that captures the key in the json array. In this case, one of `["nm73gf", "nm73gf_nmfe", "nm74gf", "nm74gf_nmfe"]`
