### ISSUE TITLE
Request: capture or report compiler and NMQual information

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/rbabylon#116]
# Summary 
rbabylon seems to be aware of nmqual and knows about the compiler.  Could we either

1. capture that info in the result log (maybe overkill) or 
1. have a function that reports out those details on request

**Comment by seth127** [comment]
I actually just opened this issue yesterday https://github.com/metrumresearchgroup/rbabylon/issues/115

I think we could probably add these fields to that too.

**Comment by seth127** [comment]
@kylebaron Here is what is currently captured by `bbi` (and hence would be easy to extract). Is what you're looking for in here? If not , we'll need to open an issue in https://github.com/metrumresearchgroup/babylon/issues which is fine, but will take slightly longer to knock out.

```
{
    "bbi_version": "v2.1.2",
    "model_name": "1.ctl",
    "original_model": "1.ctl",
    "model_path": "/data/home/sethg/rbabylon/tests/testthat/model-examples/1/1.ctl",
    "data_path": "../../data/acop.csv",
    "data_md5": "4ddb44da897c26681d892aa7be99f74b",
    "model_md5": "731923458236cc008c3adafa2f0877a7",
    "model_filename": "1",
    "model_extension": "ctl",
    "original_path": "/data/home/sethg/rbabylon/tests/testthat/model-examples/1",
    "output_dir": "/data/home/sethg/rbabylon/tests/testthat/model-examples/1",
    "configuration": {
        "clean_lvl": 1,
        "git": true,
        "babylon_binary": "/data/apps/bbi",
        "output_dir": "{{ .Name }}",
        "threads": 4,
        "local": {},
        "nonmem": {
            "nm73gf": {
                "home": "/opt/NONMEM/nm73gf",
                "executable": "nmfe73",
                "nmqual": true
            },
            "nm73gf_nmfe": {
                "home": "/opt/NONMEM/nm73gf_nmfe",
                "executable": "nmfe73"
            },
            "nm74gf": {
                "home": "/opt/NONMEM/nm74gf",
                "executable": "nmfe74",
                "nmqual": true,
                "default": true
            },
            "nm74gf_nmfe": {
                "home": "/opt/NONMEM/nm74gf_nmfe",
                "executable": "nmfe74"
            }
        },
        "parallel": false,
        "nmfe_options": {
            "maxlim": 100
        },
        "mpi_exec_path": "/usr/local/mpich3/bin/mpiexec",
        "parallel_timeout": 2147483647
    },
    "error": null
}
```

**Comment by seth127** [comment]
The one marked `default: true` is the one used for the run
```
            "nm74gf": {
                "home": "/opt/NONMEM/nm74gf",
                "executable": "nmfe74",
                "nmqual": true,
                "default": true
```

**Comment by copernican** [comment]
@seth127 I'm not clear on the requirement here. Is it sufficient to include a new variable in the tibble returned from `config_log()`? Would that just be a logical indicating whether the corresponding model (`"default": true`) has `"nmqual": true`?

**Comment by seth127** [comment]
That's a question for @kylebaron too. Maybe we can all get on a short call early next week to look through the `bbi_config.json` and firm up exactly what he wants for both this and #115

**Comment by kylebaron** [comment]
@seth127 and @copernican Let's discuss internally what we should do with nmqual.  We may no longer need this.  

For future reference: 
- For models run with nmqual, there is a file in the output directory called `root.log.xml` this has the nmqual information. 
- The nmqual version number would be in that xml file
- The nmqual version should also be obtainable by going to the nonmem executable directory, where this information should also exist

I will open an issue internally to discuss if this is even needed at this point.

**Comment by kylebaron** [comment]
Regarding compiler version:

I went to 
```
kyleb@metwrx4 /opt/NONMEM/nm74gf/run $ more nmfe74
#!/bin/bash
dir=/opt/NONMEM/nm74gf
f=gfortran
```

If we are using `gfortran` to compile, then I'd like to know that we are using `gfortran` 7.5.0`. 

```
kyleb@metwrx4 /opt/NONMEM/nm74gf/run $ gfortran --version
GNU Fortran (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
```

Like the NMQUAL issue, let's discuss internally to make sure this is really something that we need going forward.

**Comment by kylebaron** [comment]
@seth127 I think if we have the NONMEM executable name, that should be good.  We're going another direction on NMqual and maybe even reporting the compiler version.

Can we close this one and just go forward with #115 ?  If so, please do.

**Comment by seth127** [comment]
yep, closing this as commented here https://github.com/metrumresearchgroup/rbabylon/issues/115#issuecomment-686520004

**Comment by seth127** [comment]
removing from milestone before validation because this was closed without action
