### ISSUE TITLE
Request: can shrinkage be included in the tibble output by param_estimates()

### ISSUE THREAD

**Issue by KatherineKayMRG** [metrumresearchgroup/rbabylon#119]
Hi @seth127, 

We discussed this earlier - it would be very helpful if the `param_estimates()` function could also return the shrinkage estimates. Currently, for every parameter table I make, I then have to grab the shrinkage values from the full summary table and merge it into param_estimates tibble. It's not difficult but it is repetitive and it would be nice to just have it returned automatically. 

Thanks,
Katherine

**Comment by seth127** [comment]
@KatherineKayMRG would you mind pasting a sample of code that you use to do this? Just to make sure that we're pulling the same numbers, etc.

Thanks

**Comment by KatherineKayMRG** [comment]
Hey @seth127 - I use in the example project I use

```
shrinkage = sum$shrinkage_details[[1]][[1]]$eta_sd
shrinkDF <- tribble(
  ~name, ~shrink, 
  "OMEGA11", shrinkage[1], 
  "OMEGA22", shrinkage[2], 
  "OMEGA33", shrinkage[3], 
)
```
but this would have to adapt to pull the shrinkage from the last estimation method if there were multiple. 

Also, we wouldn't do this for a BAYES run

**Comment by seth127** [comment]
@KatherineKayMRG excuse the basic questions but I want to make sure we have the spec all buttoned up for this. A few questions:

## 1 - which field?

I see the following fields under `shrinkage_details` in the summary object
```
> s <- MOD1 %>% model_summary()
> str(s$shrinkage_details)
List of 1
 $ :List of 1
  ..$ :List of 11
  .. ..$ sub_pop     : int 1
  .. ..$ eta_bar     : num [1:2] 0.0018 -0.00739
  .. ..$ ebv_bar_se  : num [1:2] 0.04 0.0599
  .. ..$ pval        : num [1:2] 0.964 0.902
  .. ..$ eta_sd      : num [1:2] 17.51 2.06
  .. ..$ eps_sd      : num 4.09
  .. ..$ ebv_sd      : num [1:2] 18.52 2.54
  .. ..$ num_subjects: int [1:2] 40 40
  .. ..$ eta_vr      : num [1:2] 31.96 4.08
  .. ..$ eps_vr      : num 8.01
  .. ..$ ebv_vr      : num [1:2] 33.62 5.02
```
above you indicate that, for this column that we are creating, we are only concerned with `eta_sd`. Is that correct?

## 2 - which params are relevant?

My example model (acop) has the following params
```
THETA1      
THETA2      
THETA3      
THETA4      
THETA5      
OMEGA(1,1)  
OMEGA(2,1)  
OMEGA(2,2)  
SIGMA(1,1)  
```
but I only see two shrinkage values. Am I correct that these correspond _only_ to the `OMEGA` diagonal elements? If so:

* will THETA or SIGMA _ever_ have shrinkage values? 
* will _off-diagnonal_ OMEGAs ever have shrinkage values?
* should all the other rows just have `NA`?

## 3 - empty column

My plan is to always create the `shrinkage` column and in the cases where there is no shrinkage information it will be all `NA`. This feels better for consistency (always having `param_estimates()` return a tibble with the same columns).

## 4 - Bayesian

I understand that for Bayesian models (Bayes and NUTS) we do _not_ want to report shrinkage. In these cases, the column will be all `NA` as mentioned above. Are there any other estimation methods like this, where we don't want to add shrinkage to the table?

**Comment by KatherineKayMRG** [comment]
Hey @seth127 

I've tried to answer your questions below but happy to follow up further

_Questions 1 - 2_: Thanks for checking. I'm normally just looking for shrinkage on the omega's but it would be good to also capture shrinkage the sigmas too. I've tried to answer specific questions below but just to be clear there should be a shrinkage value for every diagonal omega (eta_sd) and diagonal sigma (eps_sd)... there is no shrinkage for theta and off-diagonals.

- will THETA params ever have shrinkage values? **No, please just put NA here**
- will SIGMA params ever have shrinkage values? Does eps_sd correspond to the SIGMA diagonals and, if so, should I pull that in as well? **Yes there is shrinkage on the sigma terms and yes it's reported as eps_sd so please return this for the corresponding eps estimate**
- will off-diagnonal OMEGAs (or SIGMAs) ever have shrinkage values? **No, please put NA here**
- should all the other rows just have NA? **Yes please**

_Question 3_: Yes I agree, I would prefer the `param_estimates()` always return a tibble with the same columns and I agree it should just have NA if no estimate is present.

_Question 4_: I think it would just be Bayes and NUTS but we can follow up at the 10am meeting, I'm not sure about methods like SAEM. 

_Question 5_: I have only done a mixture model once a long time ago. I'll go back and take a look at what it shows in the lst file and get back to you.

**Comment by seth127** [comment]
Decision on question 4: the output of the `param_estimates()` function is not quite right in several ways for Bayesian models so the decision for now is to have it error if the estimation method is either Bayes or NUTS. We will have a future issue that re-engineers this function for parsing Bayesian output.

Follow-up should the same thing happen for mixture models? Would this just be any model with multiple subpops, regardless of estimation method?

**Comment by KatherineKayMRG** [comment]
Hey @seth127 

We discussed this more today and all agreed that we would like to keep this as simple as possible in the short term to allow param_estimates to include shrinkage in the next release of rbabylon. 

In the short term, we’d like to have shrinkage included (as discussed above) for all models that were not run with Bayes/NUTs. 

If it’s a mixture model, please return the parameter table with NAs in the shrinkage column and potentially a warning message that shrinkage should be extracted by the user from the model_summary function and appended to the table manually. We all agreed that mixture models are not used often and, when they are, some additional work by the user to extract shrinkage themselves (like I currently do) seems reasonable for now. This should happen for all mixture models regardless of estimation method (obviously not applicable for Bayes/NUTS). 

In the longer term, it would be nice to have a separate function that returns the shrinkage for each subpopulation in a separate table that the user can join to the param_estimates table manually.

Let us know if that doesn't answer your question or if there are still things we should clarify.

**Comment by seth127** [comment]
That's perfect @KatherineKayMRG thanks.

**Comment by seth127** [comment]
Both associated PR's have merged to develop

**Comment by seth127** [comment]
Updating description for validation. Original description:

Hi @seth127, 

We discussed this earlier - it would be very helpful if the `param_estimates()` function could also return the shrinkage estimates. Currently, for every parameter table I make, I then have to grab the shrinkage values from the full summary table and merge it into param_estimates tibble. It's not difficult but it is repetitive and it would be nice to just have it returned automatically. 

Thanks,
Katherine
