### ISSUE TITLE
Feature: one-pager run summary

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/rbabylon#121]
# Summary
As a user, I want to be able to call a single R function and get a top-line summary of what happened in a nonmem run.  I want to summary to be plain text and resemble the output from `bbi nonmem summary`

# Tests

**Comment by seth127** [comment]
Use this (output of `bbi nonmem summary ...` _without_ `--json` flag) as the template

<img width="628" alt="Screen Shot 2020-08-18 at 10 05 49 AM" src="https://user-images.githubusercontent.com/7806083/90527717-d884ea00-e13f-11ea-8334-7f340ca18210.png">

**Comment by seth127** [comment]
Some notes from @anarpkpd @kylebaron 

* if $COV step fails or isn't there, return blank or NA column for STDERR
* return everything that gets extracted into `summary_log()` row as the baseline (ofv, condition, etc.)

**Comment by seth127** [comment]
The plan is to implement this as a print method, as described in https://github.com/metrumresearchgroup/rbabylon/issues/110

(that issue discusses several s3 classes, this will only be for the `bbi_nonmem_summary` object.

**Comment by kylebaron** [comment]
My name is @kylebaron and I approve this plan.

**Comment by seth127** [comment]
Looking for clarification on some internal discussions about how to display the parameter table. Specifically, discussion of `.fixed` and `.off_diag` arguments. The soft consensus was to have both of these args and have both default to `FALSE`. Are we sure that's what we want?

Some examples are below (I truncated the top part because only the OMEGAS and SIGMAS change):

```r
# load a model summary
.s <- system.file("model", "nonmem", "complex", "example2_saemimp", package = "rbabylon") %>% 
    read_model() %>% 
    model_summary()
```

None of the OMEGAS are fixed here. There is only one SIGMA and it's fixed to 1.
```
> .s   # (this would be the default)
|parameter_names |estimate |stderr   |shrinkage |
|:---------------|:--------|:--------|:---------|
|THETA1          |3.30     |0.0327   |          |
...
|THETA11         |0.0992   |0.00277  |          |
|OMEGA(1,1)      |0.0104   |0.000970 |7.31      |
|OMEGA(2,2)      |0.00828  |0.00136  |33.7      |
|OMEGA(3,3)      |0.0131   |0.00324  |40.6      |
|OMEGA(4,4)      |0.0110   |0.00204  |27.8      |

> print(.s, .fixed = T)
|parameter_names |estimate |stderr   |shrinkage |
|:---------------|:--------|:--------|:---------|
|THETA1          |3.30     |0.0327   |          |
...
|THETA11         |0.0992   |0.00277  |          |
|OMEGA(1,1)      |0.0104   |0.000970 |7.31      |
|OMEGA(2,2)      |0.00828  |0.00136  |33.7      |
|OMEGA(3,3)      |0.0131   |0.00324  |40.6      |
|OMEGA(4,4)      |0.0110   |0.00204  |27.8      |
|SIGMA(1,1)      |1.00     |0.00     |27.4      |

> print(.s, .off_diag = T)
|parameter_names |estimate  |stderr   |shrinkage |
|:---------------|:---------|:--------|:---------|
|THETA1          |3.30      |0.0327   |          |
...
|THETA11         |0.0992    |0.00277  |          |
|OMEGA(1,1)      |0.0104    |0.000970 |7.31      |
|OMEGA(2,1)      |0.000320  |0.000831 |          |
|OMEGA(2,2)      |0.00828   |0.00136  |33.7      |
|OMEGA(3,1)      |0.00198   |0.00135  |          |
|OMEGA(3,2)      |0.000872  |0.00149  |          |
|OMEGA(3,3)      |0.0131    |0.00324  |40.6      |
|OMEGA(4,1)      |-0.000190 |0.00104  |          |
|OMEGA(4,2)      |0.00101   |0.00114  |          |
|OMEGA(4,3)      |0.00404   |0.00228  |          |
|OMEGA(4,4)      |0.0110    |0.00204  |27.8      |

> print(.s, .fixed = T, .off_diag = T)
|parameter_names |estimate  |stderr   |shrinkage |
|:---------------|:---------|:--------|:---------|
|THETA1          |3.30      |0.0327   |          |
...
|THETA11         |0.0992    |0.00277  |          |
|OMEGA(1,1)      |0.0104    |0.000970 |7.31      |
|OMEGA(2,1)      |0.000320  |0.000831 |          |
|OMEGA(2,2)      |0.00828   |0.00136  |33.7      |
|OMEGA(3,1)      |0.00198   |0.00135  |          |
|OMEGA(3,2)      |0.000872  |0.00149  |          |
|OMEGA(3,3)      |0.0131    |0.00324  |40.6      |
|OMEGA(4,1)      |-0.000190 |0.00104  |          |
|OMEGA(4,2)      |0.00101   |0.00114  |          |
|OMEGA(4,3)      |0.00404   |0.00228  |          |
|OMEGA(4,4)      |0.0110    |0.00204  |27.8      |
|SIGMA(1,1)      |1.00      |0.00     |27.4      |
```

**Comment by timwaterhouse** [comment]
This looks good to me. Thanks @seth127.

**Comment by riggsmm** [comment]
We had decided in other places to drop the RSE, do so here too?

**Comment by timwaterhouse** [comment]
@riggsmm The RSE is gone, this is just showing standard error. I wasn't part of the earlier discussions, but IMO in this context ("a top-line summary of what happened in a nonmem run") I think standard error can be useful information even if it doesn't end up in a report.

**Comment by riggsmm** [comment]
got it! Thanks, I was looking at the example before -- I see that RSE is gone in the latest one :-) 

(agree on keeping std errors)

**Comment by KatherineKayMRG** [comment]
Looks good @seth127
