### ISSUE TITLE
Create new YAML model input file by inheriting from parent YAML

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/rbabylon#13]
# Summary
- For the purposes of model development and iteration, a user can create a new YAML model file (and corresponding control stream file) based on a "parent" YAML model file.
- User must provide a text description for the new model
- Parent control stream will be copied and (optionally) the `$PROBLEM` line will be filled with the new model run id and description. The rest of the new control stream file will be an exact copy of the parent.
- `model_path` field in the new YAML will point to the newly copied control stream.
- `description` field in the new YAML will be filled with user provided description.
- `based_on` filed in the new YAML will be filled with run id from the parent model.
- User can optionally specify additional model run id's to be appended to the `based_on` field.
- User can opt to inherit any tags from the parent model and/or specify new tags for the `tags` field in the new model YAML.

# Tests
- tests/testthat/test-workflow.R
  - copy_from_model creates accurate copy
  - copy_from_model options work

**Comment by dpastoor** [comment]
> based_on filed in the new YAML will be filled with run id from the parent model.

I'm not sure how the yaml parser determines whether scalar values should be represented as a list of 1, or a single key-value pair. We should be sure to add a test to make sure it always comes out as a list

In particular, making sure copy_from_model(..., based_on = "prev_model")

does not do: 

```
based_on: prev_model
```

and still would do:

```
based_on:
- prev_model
```

**Comment by seth127** [comment]
> I'm not sure how the yaml parser determines whether scalar values should be represented as a list of 1, or a single key-value pair...

Added `scaler_to_list()` in utils.R that enforces these as a list of 1.

**Comment by seth127** [comment]
This works and has been merged to `develop` from `post-processing-v1`
