### ISSUE TITLE
error when calling submit_model() with a model object and model_directory option unset

### ISSUE THREAD

**Issue by copernican** [metrumresearchgroup/rbabylon#133]
The `.directory` argument to `submit_model()` is described as

> Model directory which `.mod` path is relative to. Defaults to `options('rbabylon.model_directory')`, which can be set globally with `set_model_directory()`. **Only used when passing a file path for `.mod` instead of a `bbi_{.model_type}_model` object.**

But if `submit_model()` is called with a model object and the option `rbabylon.model_directory` is unset, an error is thrown.

```r
library(rbabylon)
options(rbabylon.bbi_exe_path = "/data/apps2/bbi")
model_dir <- "~/model"  # contains 1.ctl

bbi_init(model_dir, "/opt/NONMEM", "nm74gf")

mod1 <- new_model(
  "1.yaml", 
  "our first model", 
  .overwrite = TRUE,
  .directory = model_dir
)

res <- submit_model(mod1, .mode = "local")
#> Error in value[[3L]](cond): No babylon.yaml file exists at ./babylon.yaml -- Either use `bbi_init('model/dir/')` to create one, or pass a valid path to the `.config_path` argument of `submit_model()`
```

This appears to be a consequence of the default value for the `.config_path` argument to `submit_model.bbi_nonmem_model`, i.e.,

```r
.config_path = file.path(get_model_directory() %||% ".", "babylon.yaml")
```

If `rbabylon.model_directory` is unset, then `get_model_directory()` will be `NULL`, so that `.config_path` will have the value `"./babylon.yaml"`. This will not in general be correct. Because `.mod[["model_working_dir"]]` contains the path to the `babylon.yaml` file created by `bbi_init()`, one solution could be to modify `submit_model.bbi_nonmem_model()` as

```r
submit_model.bbi_nonmem_model <- function(...) {
  # code
  res <- submit_nonmem_model(..., .config_path = .mod[["model_working_dir"]])
  # further code
}
```

which would also make the documentation for `.directory` true.

**Comment by seth127** [comment]
Yes, I see the issue here. More motivation for getting rid of `options('rbabylon.model_directory')`. I've added this to a new milestone for that effort: https://github.com/metrumresearchgroup/rbabylon/milestone/11

We should begin making new issues to capture that work and put them on that milestone.

**Comment by copernican** [comment]
The `rbabylon.model_directory` option has been deprecated, and the example above now works if the call to `new_model()` is

```r
mod1 <- new_model(
  file.path(model_dir, "1"), 
  "our first model", 
  .overwrite = TRUE
)
```
