### ISSUE TITLE
Parse model YAML files into run log table

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/rbabylon#14]
# Summary
- User can parse all model YAML files in a directory (and optionally subdirectories) into a run log table.
- Table correctly parses all required YAML fields:
  - `model_path` -- character scaler with path to control stream
  - `description` -- character scaler with text description of model
  - `based_on` -- (optional) list of model run id's  that are parents of model. If not provided, assumed to be a root node
  - `tags` -- (optional) list of any user tags associated with model
  - `bbi_args` -- (optional) list of arguments passed through to babylon for this model run
- Table also has a `run_id` column that can be mapped to any mention of a given model in the `based_on` column.
- Adding additional diagnostics about the model run is _not_ in scope for this issue, but is intended as future functionality.

# Tests
- tests/testthat/test-workflow.R
  - create_run_log matches reference tibble

**Comment by dpastoor** [comment]
@seth127 made some minor tweaks to spec - in particularly noting based_on/tags/bbi_args are optional fields. model_path and description should be required. 

with respect to the model_path - we should be clear of `character scaler with path to control stream` what that path means.

I propose it should either be an absolute path, or that should be the model path relative to the yaml file, recommended to be in the same directory. If different/other constraints are met those should be explicitly stated

**Comment by seth127** [comment]
This works and has been merged to `develop` from `post-processing-v1`
