### ISSUE TITLE
Enforce model file lives next to yaml file

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/rbabylon#141]
Enforce that the following paths are always equal to each other for any model, and reflect what is stored in the `absolute_model_path` column of the `_log_df` tibbles.

* the path to the output directory
* the path to the YAML file (without extension)
* the path to the model file (without extension)

In practice this will mean that a user _cannot_ name the model file or output directory anything different from each other, or from the YAML file. This is possible with `bbi` CLI, but it will _not_ be allowed in `rbabylon`.

## Acceptance Criteria

* ~~add a check (similar to `check_yaml_in_sync()`) that verifies the above is true at important points.~~ This won't be necessary because of #182 
  * we may want to use this issue as a chance to make sure paths to non-existing files/dirs get caught reasonably.
* deprecate  `.model_path` argument of `new_model()`
* clean up control flow in [lines 34-40 of create_model_object()](https://github.com/metrumresearchgroup/rbabylon/blob/develop/R/classes.R#L34) so that only lines 38-39 remain
* change warning on [line 243 of find_model_file_path](https://github.com/metrumresearchgroup/rbabylon/blob/develop/R/get-path-from-object.R#L243) to an error like `stop(glue("No model file found at {.ctl_path} or {.mod_path}. Please put relevant model file in that location before creating a model object."))`. Consider renaming this `find_model_file_path()` helper to something more in line with `model_file_exists()` pattern.

# Original post

Original post that the first few comments are replying to has been copied here https://github.com/metrumresearchgroup/rbabylon/issues/141#issuecomment-697630676

**Comment by seth127** [comment]
I'm looking for feedback on this, mostly on the *Counterpoint?* section. @copernican @dpastoor @kylebaron @anarpkpd @timwaterhouse @shairozan tag any others who may want to weigh in.

**Comment by anarpkpd** [comment]
I have noticed that when we run BAYES we tend to do so in the folder that contains the final developed model. Bayes is run 4 times ( 4 chains) . Ofteh the analyst give the same run number to the four chains+letter, the final developed model+letter(i.e, 23a,23b,23c,23d). Is  possible to do this with rbabylon? ( a run within a run directory?) and since we are just perturbing the init est, can we use the same yaml file for the four chains?

**Comment by seth127** [comment]
That is a good question @anarpkpd and we have thought about doing something like this. This is a different issue than what we're discussing here though, although it is connected.

We haven't gotten too deep into how to orchestrate Bayesian runs but I think this is part of what @timwaterhouse is going to work on with us in the next few weeks/months. Let's find some time to discuss this (maybe on the 10am call) and get a spec together for exactly how we would want it to work.

**Comment by seth127** [comment]
We have agreement from @riggsmm and his 10am crew that this is the right move. We shall forge ahead.

**Comment by seth127** [comment]
This was the original issue, copied here after we modified the description to be a clear dev spec.

## Summary
In several different places (primarily various log_df's) models are identified by an `absolute_model_path`. This path is variously understood to mean either:

* the path to the output directory
* the path to the YAML file (without extension)
* the path to the model file (without extension)

Usually all three of these things are true, however there are edge cases when they could be different (most obviously if the user passes something different to the `.model_path` argument of `new_model()`). 

This could cause unexpected issues and, because it is very rare and almost never _necessary_, this is a proposal to enforce that all three things above are true.

## Proposed Acceptance Criteria

* deprecate  `.model_path` argument of `new_model()`
* enforce that the three points above are all true at various points
  * `read_model()` definitely
  * maybe within `check_yaml_in_sync()` (private) which is called within most, if not all, of the functions that take a model object.
* `new_model()` is a special case because a user should have the option to create a YAML (and model object) _before_ they have created the control stream. However, pointing to control stream that is anywhere other than right next to the YAML should be forbidden.

## Counterpoint?
Are there situations where it would be either necessary, or at least ideal, to be able to do any of the following?

* name the model file something _other than_ the same as the output_dir/YAML (but with `.ctl` or `.mod` extension)
* have a model file somewhere different than right next to the associated YAML
* have a model file somewhere different than right next to its output dir

Currently it is possible for `bbi` to do this stuff but I don't see a good reason why we should support it in `rbabylon`, especially because it causes headaches of trying to carry around a bunch of different paths that are almost always exactly the same but potentially just different enough to break something. Thoughts?

**Comment by copernican** [comment]
If we consider the test model at `tests/testthat/model-examples`, the below diagram illustrates the potential meanings of `absolute_model_path`, where we show the model and YAML files with their extensions.

```sh
.
├── 1                     # the output directory
│   ├── 1.cor
│   ├── 1.cov
│   ├── 1.cpu
│   ├── 1.ctl
│   ├── 1.ext
│   ├── 1.grd
│   ├── 1.lst
│   ├── 1.shk
│   └── bbi_config.json
├── 1.ctl                 # the model file
└── 1.yaml                # the YAML file
```

**Comment by copernican** [comment]
> * add a check (similar to `check_yaml_in_sync()`) that verifies the above is true at important points.
>   
>   * within `read_model()` and `new_model()`
>   * consider putting it within `check_yaml_in_sync()` (private) which is called within most, if not all, of the functions that take a model object.

What would this new pattern look like? For example, what message would be printed under different scenarios (model and YAML file don't match, YAML matches directory but not model, etc)? Does a check "failure" throw an error, raise a warning, or other?

**Comment by copernican** [comment]
On reflection, it would not be appropriate for a function named `model_file_exists()` to throw an error if the model file does not exist: you would expect a function with that name to return `FALSE`. It is also not appropriate for this function to return the path to the model file if it does exist, because such a function would not be type-safe.

Further, it is not clear that it would be useful to know whether a file with one of multiple extensions exists in a particular directory. Rather, our interest is in the _path_ to such a file (including the extension). It may be appropriate to retain the name and behavior of `find_model_file_path()`, with the change that it throws an error (rather than raises a warning) if the model file does not exist.

**Comment by seth127** [comment]
> We should also consider the case where multiple "eligible" files exist, e.g., both foo.ctl and foo.mod. Should this be a warning?

Good point. This should error. The user should never have both a `.ctl` _and_ a `.mod` file for the same model. If they do, it's a mistake, or at the very least, we don't support it.
