### ISSUE TITLE
add script to re-run test model

### ISSUE THREAD

**Issue by copernican** [metrumresearchgroup/rbabylon#142]
It is not clear how to re-run or update the model used for testing. We should include the workflow necessary to recreate the test output, e.g., as an R script.

**Comment by seth127** [comment]
When we design this we should also consider the situation here: https://github.com/metrumresearchgroup/rbabylon/pull/158/files#r490327774

Basically the issue of wanting to use some of the same data for both testing and for vignettes. Is there an elegant way to accomplish this without just duplicating data in the repo?

**Comment by seth127** [comment]
This function should also refresh any md5 digests that are used for test references.

**Comment by seth127** [comment]
Closed by #289
