### ISSUE TITLE
cannot generate code coverage report

### ISSUE THREAD

**Issue by copernican** [metrumresearchgroup/rbabylon#151]
`covr::package_coverage()` throws an error. We should investigate why this test is failing.

```r
Error: Failure in `/tmp/RtmpIlGPWT/R_LIBS601a15d1a265/rbabylon/rbabylon-tests/testthat.Rout.fail`
mem_model(...)
 7. rbabylon:::submit_nonmem_model(...)
 8. rbabylon:::find_config_file_path(.config_path, model_dir)
 9. base::tryCatch(...)
10. base:::tryCatchList(expr, classes, parentenv, handlers)
11. base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
12. value[[3L]](cond)

══ testthat results  ══════════════════════════════════════════════════════════════════════════════════════════════════
[ OK: 986 | SKIPPED: 0 | WARNINGS: 0 | FAILED: 1 ]
1. Error: basic workflow is correct from different working directories .. change_midstream (@test-workflow-dryrun.R#140) 

Error: testthat unit tests failed
Execution halted 
6. stop(cnd) at covr.R#438
5. show_failures(out_dir) at covr.R#361
4. withCallingHandlers({
       if ("vignettes" %in% type) {
           type <- type[type != "vignettes"]
           run_vignettes(pkg, tmp_lib) ... at covr.R#340
3. force(code) 
2. withr::with_envvar(c(R_DEFAULT_PACKAGES = "datasets,utils,grDevices,graphics,stats,methods", 
       R_LIBS = libs, R_LIBS_USER = libs, R_LIBS_SITE = libs, R_COVR = "true"), 
       {
           withCallingHandlers({ ... at covr.R#332
1. covr::package_coverage() 
```

**Comment by copernican** [comment]
`package_coverage()` runs successfully if the test shown above is skipped, e.g., by inserting `skip_on_covr()` at the top of the test block.

**Comment by seth127** [comment]
This is relevant to the `model_directory` refactor because this is an old test that may not even be relevant anymore after the refactor.

**Comment by copernican** [comment]
We now see the error

```r
Error: Failure in `/tmp/Rtmp04aG0N/R_LIBS2f2f5600a4e0/rbabylon/rbabylon-tests/testthat.Rout.fail`
ssertion on '.config_path' failed: File does not exist: 'tests/testthat/babylon.yaml'.
Backtrace:
  1. withr::with_dir(...)
  6. rbabylon:::submit_model.bbi_nonmem_model(...)
  7. rbabylon:::submit_nonmem_model(...)
  8. checkmate::assert_file_exists(.config_path)
  9. checkmate::makeAssertion(x, res, .var.name, add)
 10. checkmate:::mstop(...)

══ testthat results  ═════════════════════════════════════════════════════════════════════════════
[ OK: 695 | SKIPPED: 0 | WARNINGS: 0 | FAILED: 1 ]
1. Error: basic workflow is correct from different working directories .. change_midstream (@test-workflow-dryrun.R#30) 

Error: testthat unit tests failed
Execution halted
```

and this particular test case is the cause

```r
list(
  test_wd = "..",
  bbi_path = "testthat/babylon.yaml",
  test_path = file.path("testthat", MODEL_DIR, MOD_ID),
  change_midstream = "tests/testthat/babylon.yaml"
)
```

The reason this case fails when run in `covr`, but not with `testthat`, is a consequence of `tools::testInstalledPackage()`, which `covr::package_coverage()` uses to run the code. Specifically,

1. `package_coverage()` 

    a. installs the package to a temporary library `/path/to/lib` with the option `--install-tests`, so that the contents of `tests` are present at `/path/to/lib/rbabylon/tests`.

    b. passes the location of the temporary library to `testInstalledPackage()`.

2. `testInstalledPackage()` 

    a. sets the working directory to `/path/to/lib/rbabylon`.

    b. creates a new directory `/path/to/lib/rbabylon/rbabylon-tests`.

    c. copies the contents of `/path/to/lib/rbabylon/tests` to `/path/to/lib/rbabylon/rbabylon-tests`.

    d. sets the working directory to `/path/to/lib/rbabylon/rbabylon-tests`.

    e. runs the tests.

Thus, when the particular test above is run, `babylon.yaml` will exist at `rbabylon-tests/testthat/babylon.yaml` rather than `tests/testthat/babylon.yaml`, and the test will fail. We can work around this behavior with a pattern like

```r
if (covr::in_covr()) {
  test_dir <- "rbabylon-tests"
} else {
  test_dir <- "tests"
}
```

and then construct the path to `babylon.yaml` as

```r
change_midstream = file.path(test_dir, "testthat/babylon.yaml") 
```
