### ISSUE TITLE
class-ify the return type from reading in yaml to separate nonmem vs stan

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/rbabylon#17]
# Summary
The code that builds a model object should contain a `model_type` field that will be used to specify different classes for `bbi_nonmem_model` and `bbi_stan_model`. The `model_type` field will be required to be in a YAML for it be a valid model spec file.

# Tests
* tests/testthat/test-classes.R
  * create_model_object() correctly assigns class
  * create_model_object() fails with non-valid model type
* tests/testthat/test-workflow.R
  * compare read_model() and new_model() objects
  * read_model() returns expected object
  * yaml with no model type will fail

**Comment by seth127** [comment]
@dpastoor This can close when the linked PR merges to `develop`

**Comment by seth127** [comment]
https://github.com/metrumresearchgroup/rbabylon/pull/24 merged to `develop` branch. Closing this issue.
