### ISSUE TITLE
model_summary() and model_summaries() delete .directory arg

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/rbabylon#175]
Once https://github.com/metrumresearchgroup/rbabylon/issues/173 has been implemented, there will no longer be any use for the `.directory` argument in `model_summary()` or `model_summaries()`. It should be removed.

## Acceptance Criteria

* Remove `.directory` argument from `model_summary()` and `model_summaries()`.
* Remove the `if(!is.null(.directory))` checks from all dispatches.
* Fix or delete any tests that relied on this argument.
* Update any documentation or vignettes that mention this argument.

**Comment by copernican** [comment]
# Technical specification

1. Remove `.directory` argument for each of

    - `model_summary()`

    - `model_summary.bbi_nonmem_model()`

    - `model_summaries()`

    - `model_summaries.list()`

    - `model_summaries.bbi_run_log_df()`

2. In `model_summaries.list()` and `model_summaries.bbi_run_log_df()`, remove warning if `.directory` is not `NULL`.

3. In `model_summaries.bbi_run_log_df()`, do not pass `.directory` in call to `model_summaries()`.

# Test changes

There should not be any changes to the tests.
