### ISSUE TITLE
submit_model() and submit_models() delete .directory arg

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/rbabylon#176]
Once https://github.com/metrumresearchgroup/rbabylon/issues/173 has been implemented, there will no longer be any use for the `.directory` argument in `submit_model()` or `submit_models()`. It should be removed.

## Acceptance Criteria

* Remove `.directory` argument from `submit_model()` and `submit_models()`.
* Remove the `if(!is.null(.directory))` checks from all dispatches.
* Fix or delete any tests that relied on this argument.
* Update any documentation or vignettes that mention this argument.

**Comment by copernican** [comment]
# Technical specification

1. Remove `.directory` argument for each of

    - `submit_model()`

    - `submit_model.bbi_nonmem_model()`

    - `submit_models()`

    - `submit_models.list()`

2. In `submit_models.list()`, remove warning if `.directory` is `NULL`.

# Test changes

There should not be any changes to the tests.
