### ISSUE TITLE
yaml modification functions for adding tags, decisions

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/rbabylon#18]
# Summary
User should be able to make modifications to the model object and relevant YAML file with composable functions that take either the model object or a character string pointing to the YAML. The following fields should be able to be modified:
* tags
* decisions
* based_on
* description

# Tests
* tests/testthat/test-workflow.R
  * modify_model_field() works correctly
  * modify_model_field() de-duplication works
  * add_tags() and replace_tags() work correctly
  * add_decisions() and replace_decisions() work correctly
  * replace_description() works correctly
  * reconcile_mod_yaml() pulls in new tags

**Comment by seth127** [comment]
@dpastoor this issue can be closed when we merge the linked PR to `develop`

**Comment by seth127** [comment]
https://github.com/metrumresearchgroup/rbabylon/pull/24 merged to `develop` branch. Closing this issue.
