### ISSUE TITLE
safe_read_model delete .directory arg 

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/rbabylon#180]
`safe_read_model()` is a private function that has a `.directory` argument that defaults to `get_model_directory()`. Since this will be deprecated in #174 this will have to change.

Currently `safe_read_model()` is only called in the private helper function `find_models()` and `.directory = NULL`, so this change should not effect any currently observable behavior. We still need to do it now for housekeeping though (since otherwise the default value would refer to a function that won't exist).

Furthermore, we will delete the `.directory` arg and change the behavior of `safe_read_model()` to accept only absolute paths. This will make its behavior safer and more explicit in the future.

## Acceptance Criteria

* delete `.directory` arg from `safe_read_model()`
* delete `.directory = NULL` from `safe_read_model()` call inside `find_models()`
* enforce `safe_read_model(.yaml_path)` arg to be an absolute path to avoid any ambiguity
  * this is currently what its passed in `find_models()` so no changes necessary there.
* update `safe_read_model()` docs accordingly

**Comment by copernican** [comment]
#224 closes
