### ISSUE TITLE
Implementation: combine YAML_YAML_PATH, YAML_MOD_PATH, YAML_OUT_DIR

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/rbabylon#182]
This issue came out of a comment here: https://github.com/metrumresearchgroup/rbabylon/issues/179#issuecomment-697845924

Essentially, because of #141, we will be enforcing that `.mod[[YAML_YAML_PATH]]`, `.mod[[YAML_MOD_PATH]]`, `.mod[[YAML_OUT_DIR]]` are all the same path but with different extensions. This makes it both silly and dangerous to carry all three of them around. Silly for obvious reasons; dangerous because a user could do something like manually change `.mod[[YAML_MOD_PATH]]` and move the control stream, thus breaking our ability to enforce #141 (and inadvertently breaking their model object).

The purpose of this issue will be to reconsider how that is stored in the model object. Some things to consider:

* carry around only `ABS_MOD_PATH` as used in the `_log` functions.
* change all the `get_path_from_object()` functions to add some extension to `.mod[[ABS_MOD_PATH]]` instead of querying some other key.
* do we even need `.mod[[WORKING_DIR]]` if we do this?
  * alternately, should we keep `.mod[[WORKING_DIR]]` and also keep `mod[[MODEL_FILE]]` such that the control stream path would unambigously be `file.path(.mod[[WORKING_DIR]], mod[[MODEL_FILE]])` and the other paths could all be inferred from that?

Need to discuss more... **Should consider doing this before, or in tandem with, #141.**

**Comment by copernican** [comment]
There may be a benefit to storing at least (only?) the absolute path to the model file in the model object. We anticipate that that file will be edited by the user, and 

- do not anticipate that the user will (directly) edit the YAML file
- will not support the user changing the location of the output directory to be inconsistent with the definition in #141

While storing the path to the model file in some sense creates a "leak" in the abstraction of #141, given the outsize importance of the model file, it may be appropriate. If we adopt this, then it should be straightforward to resolve the other meanings of `absolute_model_path`:

- the working directory is obtained by dropping the model file extension
- the YAML file is obtained by replacing the model file extension with `.yaml`

We might imagine helper functions like 

```r
model_file_to_output_dir <- function(path) {
  dirname(path)
}

model_file_to_yaml <- function(path) {
  # replace model file extension with `.yaml`
}
```

which would be lightweight and encapsulate the definition proposed in #141. We should consider if we will ever need to go "the other way," e.g., convert a path to the YAML file to a path to the model file.

**Comment by seth127** [comment]
Working off of what @copernican said above. Here's some pseudo-code for one way to attack this

```

############ new_model() option 1

.path <- "../foo/bar"               # this is passed

# this will return an absolute path to the .ctl or .mod
# and check that it exists
.abs_path_to_model_file <- find_model_file_path(.path) 
# "/path/to/foo/bar.ctl"
# gets thrown away ^

# this is the only path we carry around?
.mod[[ABS_MOD_PATH]] <- dirname(.abs_path_to_model_file)
# "/path/to/foo/bar"

############ other calling code

# we want the output directory
.mod[[ABS_MOD_PATH]]

# we want to read/digest the yaml
yaml_ext(.mod[[ABS_MOD_PATH]])

# we want to write to yaml
save_model_yaml(.mod)

# we want the control stream
find_model_file_path(.mod[[ABS_MOD_PATH]])
```

**Comment by copernican** [comment]
This specification is WIP.

# Summary

As part of a broader refactor, we will remove from the model object the elements

- `model_path` 
- `model_working_dir` 
- `orig_yaml_file`
- `output_dir`

and instead store only `absolute_model_path`, as defined in #141.

# Technical specification

## new_model()

1. Remove the `model_path` argument. This was originally discussed in #141, and will be implemented as part of a single PR.

2. Remove the assignment to `model_working_dir`, because this element will no longer be created.

3. Remove the assignment to `orig_yaml_file`, because this element will no longer be created.

4. Remove the assignment to `model_path`, because this element will no longer be created.

5. Add an element `absolute_model_path` to the list passed to `save_model_yaml()`. The value of this element will be (the absolute path to) as defined in #141. For example, if the path to the model file is `/path/to/foo/bar.ctl`, then the `absolute_model_path` is `/path/to/foo/bar`.

5. Pass the parent directory of `absolute_model_path` as the `.start` argument to `safe_based_on()`.

6. #181 will remove the `.out_path` argument to `save_model_yaml()`, and should be implemented before this PR.

7. After calling `save_model_path()`, the YAML file will exist. In a separate PR, we will modify `save_model_yaml()` to invisibly return the path to the YAML file, which we can then pass to `digest()` to obtain the MD5 sum of that file.

## create_model_object()

`create_model_object()` contains references to elements of its argument `res` that will be deprecated.

1. Remove the logic that creates the element `model_path`, because this element will not exist in `res`.

deprecate .model_path argument of new_model()

clean up control flow in lines 34-40 of create_model_object() so that only lines 38-39 remain
change warning on line 243 of find_model_file_path to an error like stop(glue("No model file found at {.ctl_path} or {.mod_path}. Please put relevant model file in that location before creating a model object.")). Consider renaming this find_model_file_path() helper to something more in line with model_file_exists() pattern.

**Comment by seth127** [comment]
note: we need to remember to address the getters in `get-path-from-object.R` that will all break when we do this because they rely on `orig_working_dir`.

**Comment by seth127** [comment]
Comments:

## get_model_id.bbi_nonmem_model()
Should we consider add a `bbi_log_df` dispatch too, using our helpful `get_path_from_log_df()` friend? Could be useful if we ever get around to https://github.com/metrumresearchgroup/rbabylon/issues/146

## get_based_on.default
This is a good point, but I think you're right that the path of least resistance is the right one at this moment. (Which would be making the small change you describe.)

## run_log_entry
**This is not right**

> !!ABS_MOD_PATH := get_model_path(.mod)

It should be `!!ABS_MOD_PATH := .mod[[ABS_MOD_PATH]]`

**Comment by copernican** [comment]
> ## get_model_id.bbi_nonmem_model()
> Should we consider add a `bbi_log_df` dispatch too, using our helpful `get_path_from_log_df()` friend? Could be useful if we ever get around to #146

Good idea. Let's do it in a separate issue, so that the focus of this issue remains deprecating these model object elements.

> ## run_log_entry
> **This is not right**
> 
> > !!ABS_MOD_PATH := get_model_path(.mod)
> 
> It should be `!!ABS_MOD_PATH := .mod[[ABS_MOD_PATH]]`

Agreed, I'll fix the spec.

**Comment by seth127** [comment]
Keeping track...

# Summary

As part of a broader refactor, we will remove from the model object the elements

- `model_path` 
- `model_working_dir` 
- `orig_yaml_file`
- `output_dir`

and instead store only `absolute_model_path`, as defined in #141.

# Technical specification

## find_model_file_path()

1. ~~Currently a warning is raised if a model file is not found at `.path`. As discussed in https://github.com/metrumresearchgroup/rbabylon/issues/141#issue-693578028, this should be changed to an error, which will have the effect of requiring that a model file exist to create a model object.~~

## create_model_object()

`create_model_object()` contains references to elements of its argument `res` that will be deprecated.

1. Remove logic that creates `res[[YAML_MOD_PATH]]`.

2. Remove logic that checks the model file extension.

3. Remove logic that creates `res[[YAML_OUT_DIR]]`.

## new_model()

1. Remove the `model_path` argument. This was originally discussed in #141, and will be implemented as part of a single PR.

2. Remove the assignment to `model_working_dir`, because this element will no longer be created.

3. Remove the assignment to `orig_yaml_file`, because this element will no longer be created.

4. Remove the assignment to `model_path`, because this element will no longer be created.

5. Pass the parent directory of `absolute_model_path` as the `.start` argument to `safe_based_on()`.

6. ~~Add an element `absolute_model_path` to the list passed to `create_model_object()`. The value of this element will be as defined in #141. For example, if the path to the model file is `/path/to/foo/bar.ctl`, then the `absolute_model_path` is `/path/to/foo/bar`. Note that the object returned by `create_model_object()` will include the MD5 sum of the YAML file as a consequence of #195.~~

## read_model()

1. Remove the assignment to `model_working_dir`.

2. Remove the assignment to `orig_yaml_file`.

## get_*_path.bbi_nonmem_model()

The purpose of these functions is to encapsulate details about file locations specific to particular types of models.

1. In `get_model_path.bbi_nonmem_model()`, modify the assignment to `.path` to be

    ```r
    .path <- find_model_file_path(.bbi_object[[ABS_MOD_PATH]])
    ```

    which will eliminate the references to `WORKING_DIR` and `YAML_MOD_PATH`.

2. In `get_output_dir.bbi_nonmem_model()`, modify the assignment to `.path` to be

    ```r
    .path <- .bbi_object[[ABS_MOD_PATH]]
    ```

3. In `get_yaml_path.bbi_nonmem_model()`, modify the assignment to `.path` to be

    ```r
    .path <- yaml_ext(.bbi_object[[ABS_MOD_PATH]])
    ```

4. Though we are removing `model_working_dir` from the model object, we still refer to that directory in various places. We will therefore add an internal function `get_model_working_directory()` whose single argument is a model object `mod`, and whose return value is `dirname(mod[[ABS_MOD_PATH]])`.

## get_model_id.bbi_nonmem_model()

1. Modify the return value to be 

    ```r
    basename(tools::file_path_sans_ext(get_model_path(.mod)))
    ```

## build_bbi_param_list()

1. Modify the assignment to `mod_working_dirs` to be

    ```r
    mod_working_dirs <- purrr::map_chr(.mods, get_model_working_directory)
    ```

## submit_*_model\*()

1. A warning is raised if the `.directory` argument is passed to `submit_model.bbi_nonmem_model()`, and the warning message refers to `.mod[["WORKING_DIR"]]`. Because the `.directory` argument will be deprecated as part of a broader refactor, we should simply remove the warning.

2. In `submit_nonmem_model()`, replace the reference to `.mod[[YAML_MOD_PATH]]` with `get_model_path(.mod)`.

3. In `submit_nonmem_model()`, replace the reference to `.mod[[WORKING_DIR]]` with `get_model_working_directory(.mod)`.

4. In `submit_nonmem_models()`, modify the assignment to `model_dir` to be

    ```r
    model_dir <- get_model_working_directory(.run[["models"]][[1L]])
    ```

## *_based_on()

1. In `add_based_on()`, modify the `.value` argument passed to `modify_model_field()` to be

    ```r
    .value = safe_based_on(get_model_working_directory(.mod), .based_on),
    ```

2. In `replace_based_on()`, make the same change as for `add_based_on()`.

## get_based_on.default()

This method is called when the `.bbi_object` argument to `get_based_on()` is neither a `character` nor a `bbi_run_log_df`. In practice, this will be true when `.bbi_object` is a `bbi_nonmem_model`. While we may consider removing this method and adding a method for that class in the future, at the moment the path of least resistance is likely to modify the `default` method.

1. Replace references to `.bbi_object[[WORKING_DIR]]` with `get_model_working_directory(.bbi_object)`.

## build_path_from_mod_obj()

1. Modify the assignment to `out_file_path` to be

    ```r
    out_file_path <- file.path(
      get_output_dir(.mod),
      fs::path_ext_set(get_model_id(.mod), .extension)
    )
    ```

## tail_output.bbi_nonmem_model()

1. Modify the assignment to `.file` to be

    ```r
    .file <- file.path(get_output_dir(.mod), "OUTPUT")
    ```

## model_summary.bbi_nonmem_model()

1. A warning is raised if the `.directory` argument is passed, and the warning message refers to `.mod[["WORKING_DIR"]]`. Because the `.directory` argument will be deprecated as part of a broader refactor, we should simply remove the warning.

## nonmem_summary()

1. Modify the assignment to `.path` to be

    ```r
    .path <- get_output_dir(.mod)
    ```

## run_log_entry()

1. Modify the assignment to `!!ABS_MOD_PATH` to be

    ```r
    !!ABS_MOD_PATH := .mod[[ABS_MOD_PATH]]
    ```

2. Modify the error message by replacing `.mod[[YAML_YAML_NAME]]` with `get_yaml_path(.mod)`.

## enforce_length()

1. This function refers to `YAML_YAML_NAME`, which will be deprecated. But, we may be able to replace this function with equivalent assertions. Everywhere that `enforce_length()` is called, `.len` has the default value `1`. Assuming that the assignment to `!!ABS_MOD_PATH` is modified as described above, the remaining calls could be replaced by

    ```r
    checkmate::assert_scalar(.mod[[YAML_YAML_MD5]])
    checkmate::assert_scalar(.mod[[YAML_MOD_TYPE]])
    checkmate::assert_scalar(.mod[[YAML_DESCRIPTION]])
    ```

## Constants

1. Remove assignment to `WORKING_DIR`.

2. Remove assignment to `YAML_MOD_PATH`

3. Remove assignment to `YAML_OUT_DIR`.

4. Remove assignment to `YAML_YAML_NAME`.

5. Replace `WORKING_DIR` with `ABS_MOD_PATH` in `MODEL_REQ_INPUT_KEYS` assignment.

6. Replace (1)-(4) with `ABS_MOD_PATH` in `MODEL_REQ_KEYS` assignment.

7. Replace (1)-(4) with `ABS_MOD_PATH` in `YAML_ERASE_OUT_KEYS` assignment.

# Test changes

1. Add test that `new_model()` throws an error if a model file is not present.

2. Add test that `copy_model_from()` throws an error if the parent model file is not present.

3. (WIP) add or modify other tests as required.
