### ISSUE TITLE
standardize YAML file extension

### ISSUE THREAD

**Issue by copernican** [metrumresearchgroup/rbabylon#183]
`find_yaml_file_path()` allows the YAML file to have an extension of either `.yaml` or `.yml`. Given that this file should be created and modified exclusively by `rbabylon`, it may not be necessary to allow this flexibility. We might consider standardizing on `.yaml`, and ignoring `.yml` files. Currently, the only exported function that calls `find_yaml_file_path()` is `new_model()`, so we have some flexibility.

**Comment by seth127** [comment]
heh. https://github.com/metrumresearchgroup/rbabylon/issues/77

Worth considering this. Just thought it was a little humorous that we just did this a few months ago.

**Comment by copernican** [comment]
# Summary

#182 will consolidate multiple paths to `absolute_model_path`. The goal is to use this single path to determine multiple objects, as discussed in #141. Consequently, we do not want to support the `yml` extension, because this is an implementation detail that should not be visible to the user, and thus, we do not need the flexibility.

# Technical specification

1. `safe_based_on()` should check only for a file with the `yaml` extension.

2. Update description of `.config_path` argument to `submit_model()` to reflect `yaml` extension.

3. Update `check_status_code()` error message to reflect `yaml` extension.

4. Update `bbi_init()` documentation to reflect `yaml` extension.

5. Remove `yml_ext()`.

6. Modify `read_model()` to check for the `yaml` extension only.

7. Remove `find_yaml_file_path()`.

8. Modify `new_model()` to check for `yaml` extension only.

9. Update documentation for `submit_models()` to reflect `yaml` extension.

10. Remove `FIND_YAML_ERR_MSG`.

11. Modify `get_model_ancestry.default()` so that `get_based_on()` is not wrapped in `tryCatch()`.

# Test changes

WIP
