### ISSUE TITLE
add bbi_log_df class

### ISSUE THREAD

**Issue by copernican** [metrumresearchgroup/rbabylon#191]
# Summary

The `bbi_run_log_df`, `bbi_config_log_df`, and `bbi_summary_log_df` classes share certain characteristics. In particular, they all extend the `tbl_df` class, and all include a variable holding `absolute_model_path` as discussed in #141. It will be convenient to refer to the set of these classes with a single parent class. We propose to add the class `bbi_log_df`, so a run log object `rlg` would have

```r
class(rlg)
#> [1] "bbi_run_log_df" "bbi_log_df"     "tbl_df"         "tbl"            "data.frame"
```

and similarly for `bbi_config_log_df` and `bbi_summary_log_df`.

# Technical specification

1. Modify `create_log_df_impl()` to add the new class `bbi_log_df`.

# Test changes

1. Add test that `run_log()` returns an object that inherits from `bbi_log_df`. Note that we currently have direct tests of `create_run_log_object()`. We might consider removing these, because `create_run_log_object()` is not exported.

2. Add test that `config_log()` and `add_config()` return an object that inherits from `bbi_log_df`.

3. Add test that `summary_log()` and `add_summary()` return an object that inherits from `bbi_log_df`.

**Comment by seth127** [comment]
Currently all the functions in `classes.R` are private and yet we test them (all?) in `test-classes.R`. Should we just delete that entire test file? Those tests do provide some safety net, but they may be more trouble than they're worth to maintain going forward. And they certainly violate the "only test the public interface" principle.

**Comment by copernican** [comment]
I'm fine with deleting all of those tests. We should be implicitly testing those code paths in our tests of the exported functions, which we can check with a code coverage report.
