### ISSUE TITLE
unify new_model() and copy_nonmem_model_from()

### ISSUE THREAD

**Issue by copernican** [metrumresearchgroup/rbabylon#201]
# Summary

`new_model()` and `copy_nonmem_model_from()` do very similar things: each creates a list representing a new model that is eventually passed to `create_model_object()`. The current implementations of `new_model()` and `copy_nonmem_model_from()` are independent, which complicates making changes like #141. We propose unifying the implementation so that `copy_nonmem_model_from()` calls `new_model()`.

# Technical specification

The table below compares how the list passed to `create_model_object()` is created by each function.

| element           | `new_model()`                        | `copy_nonmem_model_from()`                    |
| ----------------- | ------------------------------------ | --------------------------------------------- |
| `based_on`          | call `safe_based_on()` with `.based_on` | call `safe_based_on()` with `c(.parent_based_on, .based_on_additional)` |
| `bbi_args`          | `.bbi_args`                          | `bbi_args` element of parent model |
| `description`       | `.description`                       | `.description` |
| `model_path`        | `.model_path`                        | call `basename()` with `.new_model` plus extension of parent model |
| `model_type`        | `.model_type`                        | `model_type` element of parent model |
| `model_working_dir` | `normalizePath(dirname(.yaml_path))` | `normalizePath(dirname(.new_model))` |
| `orig_yaml_file`    | `basename(.yaml_path)`               | `basename(yaml_ext(.new_model))` |
| `output_dir`        | `NULL`                               | `basename(tools::file_path_sans_ext(.new_model))` |
| `tags`              | `.tags`                              | `.add_tags`, if `.inherit_tags = FALSE`, or `.add_tags` and the tags from the parent model |

This suggests that `copy_nonmem_model_from()` could equivalently call `new_model()` as

```r
mod <- new_model(
  .yaml_path = .new_model,
  .description = .description,
  .model_path = basename(new_mod_path),
  .based_on = c(.parent_based_on, .based_on_additional),
  .tags = new_tags,  # constructed from the existing conditional logic
  .bbi_args = .parent_mod[["bbi_args]],
  .overwrite = .overwrite,
  .model_type = "nonmem",
  .directory = NULL
)

mod[["output_dir"]] <- basename(tools::file_path_sans_ext(.new_model))
```

and then pass `mod` to `create_model_object()`.

1. Modify `copy_nonmem_model_from()` to create the call above.

# Test changes

No test changes should be required.

**Comment by seth127** [comment]
We actually don't need  `mod[["output_dir"]] <- basename(tools::file_path_sans_ext(.new_model))` because `create_model_object()` has identical logic that gets triggered when `.mod[['output_dir']] == NULL`.
