### ISSUE TITLE
intercept output_dir in bbi_args

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/rbabylon#203]
`bbi` allows the user to specify an output directory, which defaults to `{{ NAME }}` i.e. the name of the model file, without extension. However, if the users _does_ pass through a different value for this argument (either through `submit_model(.bbi_args)` or `bbi_args` in the model YAML or in their `babylon.yaml` file) this change with _not_ be reflected in the model object and therefore `model_summary()` will not work because it will not be able to find the output directory.

The proposal here is to add a check in `submit_model()` that will check to see if `output_dir` has been passed through to `bbi_args` (either via the argument or the model YAML) and, if it has, error and tell the user that this is not supported in rbabylon. 

Note that it would still be possible for a user to change the value in `babylon.yaml` and rbabylon would have no way of knowing about this. It's not clear that there is any solution to that issue, though it seems relatively unlikely that a user would set a global `output_dir` in their `babylon.yaml`.

Also note: previous to #182 it would be _possible_ for the user to follow this pattern and _manually_ update the `'output_dir'` field of the model object such that `model_summary()` would work. After #182 this will _not_ be possible so it becomes even more perilous to allow `output_dir` to be modified.

**Comment by copernican** [comment]
We ultimately decided that we should change 

- the documentation, to reflect that changing the output directory (by any of the means described above) is not supported.

- the code, to intercept this particular argument.

We will defer changing the overall handling of babylon CLI arguments, e.g., as in #171, to a future PR/milestone.
