### ISSUE TITLE
refactor submit_nonmem_models() and build_bbi_param_list()

### ISSUE THREAD

**Issue by copernican** [metrumresearchgroup/rbabylon#205]
# Summary

`submit_nonmem_models()` refers to elements of the `bbi_nonmem_model` object that will be deprecated, e.g., `YAML_MOD_PATH`. It would be straightforward to fix these references with the `get_*_path()` functions (refactored as described in #190), except that these references are not made with respect to a model object, so there is no corresponding `get_*_path()` method. Rather, these references are to elements of a list returned by `build_bbi_param_list()`, and are currently a convenient shortcut.

`build_bbi_param_list()` exists because we prefer to make the minimal number of calls to bbi when submitting multiple models. In particular, we prefer that bbi, not `rbabylon`, handle the parallelization of model submission. It is possible to submit multiple models with a single bbi call, provided that the models all share the same set of CLI arguments to bbi and a working directory (the parent directory of `absolute_model_path` as defined in #141). Thus, we need to identify which of a set of models can be submitted together. `build_bbi_param_list()` performs this grouping operation.

But, `build_bbi_param_list()` also refers to elements of the `bbi_nonmem_model` object that will be deprecated. One solution is to modify `build_bbi_param_list()` to be (mostly) agnostic as to the structure of the model object, and at the very least not to refer to elements that will be deprecated. This can be done by returning the model objects passed as `.mods` in the output, but grouped to enable the submission of multiple models as described above. Then, `submit_nonmem_models()` can pass those model objects to the appropriate helper functions, eliminating its direct dependence on the internal structure of the model object.

This issues describes how such a refactor could be done.

# Technical specification

## build_bbi_param_list()

1. Construct a list whose elements correspond to the model objects and hold the "cleaned" set of arguments for the appropriate model, where "cleaned" means that 

    a. conflicts between runtime arguments and arguments in the model YAML file have been resolved

    b. arguments have been checked and formatted in the sense of `check_bbi_args()`

    c. arguments are sorted

2. Construct a list whose elements correspond to the model objects and hold the working directory for the appropriate model.

3. Construct a list of model "keys" whose elements correspond to the model objects and hold the combination of model arguments and working directories. Models that share a key can be submitted in a single bbi call. This list can be created from the respective elements of the lists constructed in (1) and (2).

4. Map over the list of unique keys and construct a list with two elements:

    a. `bbi_args` holds the CLI arguments corresponding to the key

    b. `models` is a list of the model objects that share the key

    Thus, the return value of `build_bbi_param_list()` a list whose elements correspond to the set of unique model keys, where each element is itself a list constructed in the manner described.

    ```
    - key_1
      - bbi_args: bbi_args_1
      - models
        - mod_A
        - mod_C
    - key_2
      - bbi_args: bbi_args_2
      - models
        - mod_B
    ```

## submit_nonmem_models()

1. Modify the assignment to `cmd_args` to be

    ```r
    cmd_args <- c(
      "nonmem",
      "run",
      .mode,
      purrr::map_chr(.run[["models"]], get_model_path),
      .run[["bbi_args"]]
    )
    ```

2. Modify the assignment to `model_dir` to be 

    ```r
    model_dir <- .run[["models"]][[1L]][[WORKING_DIR]]
    ```

   Note that `WORKING_DIR` will be deprecated by #182, and is expected to be replaced by a call like `get_model_working_directory(.run[["models"]][[1L]])`. We might also choose to extract the anonymous function passed to `map()` when building `cmd_args_list`.

# Test changes

1. The tests for `submit_models(dryrun = TRUE)` fail because they expect the bbi call to be of the form

    ```
    bbi nonmem run sge 1.ctl --flags
    ```

    Because `get_model_path()` returns an absolute path, the implementation above results in a call like

    ```
    bbi nonmem run sge /path/to/1.ctl --flags
    ```

    But, the integration tests that actually call bbi pass, which suggests that we might reasonably update the expectation. One complication is that the absolute path may not be reproducible, e.g., include a user's home directory, but that should be obtainable by resolving the path within the test.

2. The tests of `build_bbi_param_list()` should be removed, because it is an internal function.

**Comment by dpastoor** [comment]
note - we should not be providing absolute paths by the time the nmfe call is invoked - it should be relative only. There is an issue with nonmem and absolute paths https://github.com/metrumresearchgroup/babylon/issues/104#issuecomment-591190187

I believe already smooth this out anyway in babylon itself converting an absolute path back to relative, but I would just check to confirm that a change to `bbi nonmem run sge /path/to/1.ctl --flags` does not have that issue. The check can be to look at the generated .sh script to confirm that nmfe <relpath> not nmfe <abspath> is called

**Comment by seth127** [comment]
ok, I tested this manually and I'm pretty sure we're safe here. Some R code to set up the test:

```r
setwd("tests/testthat")
source("setup-workflow-ref.R")
options('rbabylon.bbi_exe_path' = '/data/apps/bbi')
bbi_init(".", "/opt/NONMEM", "nm74gf")

create_all_models() # sets up 4 models ready to submit, 3 in 'model-examples' and 1 in 'model-examples/level2'

log_df <- run_log("model-examples")
mod_paths <- log_df %>% get_model_path()
cat(mod_paths)
# /data/home/sethg/rbabylon/tests/testthat/model-examples/1.ctl /data/home/sethg/rbabylon/tests/testthat/model-examples/2.ctl /data/home/sethg/rbabylon/tests/testthat/model-examples/3.ctl /data/home/sethg/rbabylon/tests/testthat/model-examples/level2/1.ctl

##### ugh, have to manually add a ../ the $DATA in the level2 mod
# should be    $DATA ../../../data/acop.csv IGNORE=@

#### BBI CALL (copy to command line)
# cd ~/rbabylon/tests/testthat
glue("/data/apps/bbi nonmem run sge {paste(mod_paths, collapse = ' ')} --overwrite")
# $ /data/apps/bbi nonmem run sge /data/home/sethg/rbabylon/tests/testthat/model-examples/1.ctl /data/home/sethg/rbabylon/tests/testthat/model-examples/2.ctl /data/home/sethg/rbabylon/tests/testthat/model-examples/3.ctl /data/home/sethg/rbabylon/tests/testthat/model-examples/level2/1.ctl --overwrite
```

This call submits fine and the grid.sh files look right.

_one example:_
```sh
#!/bin/bash

#$ -wd /data/home/sethg/rbabylon/tests/testthat/model-examples/3

/data/apps/bbi nonmem run local 3.ctl
```

_another example, from the nested dir:_
```sh
#!/bin/bash

#$ -wd /data/home/sethg/rbabylon/tests/testthat/model-examples/level2/1

/data/apps/bbi nonmem run local 1.ctl
```

Then back to R...
```r
#### check to be sure they actually ran
sum_df <- summary_log("model-examples")
sum_df
# # A tibble: 4 x 21
# absolute_model_… bbi_summary error_msg needed_fail_fla… estimation_meth… problem_text number_of_patie… number_of_obs   ofv param_count condition_number
# <chr>            <list>      <chr>     <lgl>            <chr>            <chr>                   <int>         <int> <dbl>       <int>            <dbl>
#   1 /data/home/seth… <bb_nnmm_>  NA        FALSE            First Order Con… LEM PK mode…               40           760 2637.           7               NA
# 2 /data/home/seth… <bb_nnmm_>  NA        FALSE            First Order Con… LEM 2 level…               40           760 2637.           7               NA
# 3 /data/home/seth… <bb_nnmm_>  NA        FALSE            First Order Con… LEM 3 level…               40           760 2637.           7               NA
# 4 /data/home/seth… <bb_nnmm_>  NA        FALSE            First Order Con… LEM 1 level…               40           760 2637.           7               NA
# # … with 10 more variables: any_heuristics <lgl>, covariance_step_aborted <lgl>, large_condition_number <lgl>, correlations_not_ok <lgl>,
# #   parameter_near_boundary <lgl>, hessian_reset <lgl>, has_final_zero_gradient <lgl>, minimization_terminated <lgl>, eta_pval_significant <lgl>,
# #   prderr <lgl>
```

All looks good.
