### ISSUE TITLE
as a user I can summarize model results 

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/rbabylon#22]
# Summary

Results may be generated from after a call to `submit_model()`, however for long running processes or stuff queued to the grid, having the result object from the submission is not always possible. Hence, a user should be able to get to the summary by passing the original model object that was passed to `submit_model()` or just a path to the output directory.

## syntax

```
OUTPUT_DIR <- "../modeling/pk/101"

# create model object
mod101 <- read_model("../modeling/pk/101.yaml")

# submit model and get process object back
proc101 <- mod101 %>% submit_model()

# get summary from process object
sum101 <- proc101 %>% as_model() %>% model_summary()

# or get summary directly from the original model object
sum101 <- mod101 %>% model_summary()

# tags and decisions, etc. can be added to the model object at any point before or after the submit_model() call
mod101 <- mod101 %>% add_tags(...) %>% add_decisions(...)

# also note that mod101 can be reconstructed from the YAML at any point with read_model()
# and that read_model() can also take a path to a .ctl or .mod or just output directory
mod101 <- read_model("../modeling/pk/101.yaml")
```

# Tests
* tests/testthat/test-summary.R
  * model_summary() produces expected list object
* tests/testthat/test-workflow.R
  * as_model() returns the correct type from a process object
* tests/testthat/test-workflow-composable-bbi.R
  * step by step create_model to submit_model to model_summary works
* tests/testthat/test-workflow-composable-dryrun.R
  * basic workflow is correct from different working directories
  * Summary call is the same after changing directories

**Comment by seth127** [comment]
https://github.com/metrumresearchgroup/rbabylon/pull/24 merged to `develop` branch. Closing this issue.

**Comment by seth127** [comment]
(copied from original issue)

## syntax

```
OUTPUT_DIR <- "../modeling/pk/101"

# create model object
mod101 <- read_model("../modeling/pk/101.yaml")

# submit model and get process object back
proc101 <- mod101 %>% submit_model()

# get summary from process object
sum101 <- proc101 %>% as_model() %>% model_summary()

# or get summary directly from the original model object
sum101 <- mod101 %>% model_summary()

# tags and decisions, etc. can be added to the model object at any point before or after the submit_model() call
mod101 <- mod101 %>% add_tags(...) %>% add_decisions(...)

# also note that mod101 can be reconstructed from the YAML at any point with read_model()
# and that read_model() can also take a path to a .ctl or .mod or just output directory
mod101 <- read_model("../modeling/pk/101.yaml")
```
