### ISSUE TITLE
rename_tags function

### ISSUE THREAD

**Issue by callistosp** [metrumresearchgroup/rbabylon#262]
### Problem
The current pattern of using add_tags/remove_tags functions to edit existing tags is useful in specific scenarios. However, a more common pattern would be REPLACING a specific tag with a new tag, representing a subtle change between models.

### Proposed Solution
In this scenario, a one compartment model (101) is inadequate, so a two compartment model is used (mod102).
```
mod101 %>%
copy_model_from(102, .inherit_tags=T, .description = "two-cmpt,  prop RUV") %>%
rename_tags(TAGS$two_compartment=TAGS$one_compartment) 
```

I'm not sure I love the function name, but including "rename" will indicate to users that the syntax in this function matches `dplyr::rename` (e.g. new=old).

**Comment by callistosp** [comment]
IMO this function would make more sense to be called `replace_tags`, and the current replace be instead named `remove_all_tags`

**Comment by seth127** [comment]
Doing this dplyr style would make it much more awkward to use out `TAGS$whatever` trick that we are talking about using. 

Because of NSE, the dplyr style functions expect you to pass _unquoted_ names so you would have to do something like `replace_tags(!!TAGS$new_tag := {{TAGS$old_tag}})`. That might not even be the right syntax. Either way, sounds like a nightmare. Doing this as a single replacement that can be chained seems much easier.

```
.mod <- .mod %>%
  replace_tag(TAGS$old_tag, TAGS$new_tag) %>%
  replace_tag(TAGS$oldtag2, TAGS$new_tag2)
```

**Comment by seth127** [comment]
Original comment (repasting here after formatting issue for validation docs):

### Problem
The current pattern of using add_tags/remove_tags functions to edit existing tags is useful in specific scenarios. However, a more common pattern would be REPLACING a specific tag with a new tag, representing a subtle change between models.

### Proposed Solution
In this scenario, a one compartment model (101) is inadequate, so a two compartment model is used (mod102).
```
mod101 %>%
copy_model_from(102, .inherit_tags=T, .description = "two-cmpt,  prop RUV") %>%
rename_tags(TAGS$two_compartment=TAGS$one_compartment) 
```

I'm not sure I love the function name, but including "rename" will indicate to users that the syntax in this function matches `dplyr::rename` (e.g. new=old).
