### ISSUE TITLE
Write submit_models (multiple models at once)

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/rbabylon#27]
Currently users can only submit (or summarize) multiple models at once by doing something like `list_of_models %>% map(submit_model())`. This has several problems:
* it will get complicated and bug prone as more complicated scenarios arise
* it makes a separate `processx` call out to `bbi` for each model

## Desired state
Create `submit_models()` ~~and `model_summaries()`~~ functions that will take a list of model objects (or a character vector of paths) and will return a list of the relevant returned objects.

## Implementation
We have had some discussions about the `vctrs` package. Consider whether this is appropriate for this application.

## Calls to bbi
As mentioned, one current drawback is that the simplest implementation of this functionality makes a separate bbi call for each model object. The implemented code should ~~We need to decide whether addressing that is part of this issue, or if we should first implement the public methods naively and then have another issue to~~ convert them to most efficiently call bbi in as few calls as possible.

~~Related: is it even possible to call `bbi nonmem summary {mod} --json` on multiple models at once? If not, that will be an issue on the `babylon` repo.~~

# Tests
- tests/testthat/test-submit-model.R
  - submit_models(.dry_run=T) with list input simple
  - submit_models(.dry_run=T) with list input, 2 arg sets
  - submit_models(.dry_run=T) with character and numeric input yaml
  - submit_models(.dry_run=T) with character input ctl
  - submit_models(.dry_run=T) errors with bad input
- tests/testthat/test-workflow-composable-bbi.R
  - copying model works and new models run correctly

**Comment by dpastoor** [comment]
## what scenarios do we submit models in batch

  * a small number of models at the same checkin phase of modeling when there are differing structures to try out at same time
  * bootstrap
  * Clinical Trial Simulation/Estimation (models under different design scenarios)
  * etc

## what types of questions do we ask and when do we expect "answers" given the above scenarios

For example, we'd very likely _not_ be asking for model_summaries from an entire bootstrap in the same session as this could take days to run so will almost certainly need to reconstruct the summary object

**Comment by seth127** [comment]
I took the `model_summaries()` part out and moved it to here https://github.com/metrumresearchgroup/rbabylon/issues/53

**Comment by seth127** [comment]
(copied from original issue during validation)

# Summary 

Originally users could only submit (or summarize) multiple models at once by doing something like `list_of_models %>% map(submit_model())`. This had several problems:

* it will get complicated and bug prone as more complicated scenarios arise
* it makes a separate `processx` call out to `bbi` for each model

## New state
Create `submit_models()` function that will take a list of model objects (or a character vector of paths) and will return a list of the relevant returned objects.

## Calls to bbi
As mentioned, one current drawback is that the simplest implementation of this functionality makes a separate bbi call for each model object. The implemented code should convert them to most efficiently call bbi in as few calls as possible.
