### ISSUE TITLE
Insert NONMEM compiler info in lst file 

### ISSUE THREAD

**Issue by billkmet** [metrumresearchgroup/rbabylon#271]
For traceability for regulatory authorities, we would like to capture the gfortran version, and compiler options. The compiler options can be found at the top of the NMFE file used to run NONMEM by rbabylon. We woiuld also like the gfortran version captured as well.  Basically output from gfortran --version.  So the information might look something like below:

GNU Fortran (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
f=gfortran
o=' -w -O3 -ffast-math -ffpe-summary=none '
opstat=' -static '

This can be added to lst file at beginning or end, whichever is more convenient, but each like shouod be preceeded by a ";" so this is treated as a comment in the lat file.  So something like the followoing.

; GNU Fortran (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
; f=gfortran
; o=' -w -O3 -ffast-math -ffpe-summary=none '
; opstat=' -static '

@devinp let me know if more info is needed.

**Comment by seth127** [comment]
I'm not totally clear on this. Do we specifically want to add it to the `.lst` file, or do we just want to capture it somewhere (maybe in the `bbi_config.json`?) so that `rbabylon` has access to it? @dpastoor @kylebaron do you have thoughts on this?

**Comment by billkmet** [comment]
The capture of this info is not for our records but info for regulatory authorities. At the end of a project, all we send to the authorities is the data and ctl and lst files for NONMEM. This info is needed so authorities can reproduce our environment in case they rerun the model and get different results.

**Comment by dpastoor** [comment]
we talked about this at tools committee meeting - we actually need to move this over to the babylon repo as it should happen in bbi not in rbabylon. I will flesh out the specifics of the spec for implementation

**Comment by seth127** [comment]
Per comment above, this has been moved to babylon 
https://github.com/metrumresearchgroup/babylon/issues/198
