### ISSUE TITLE
model_summary()$run_details parsing error

### ISSUE THREAD

**Issue by callistosp** [metrumresearchgroup/rbabylon#296]
## Problem:
The model summary object contains information parsed from the model file stored in `run_details`. One of the variables under `run_details` is `$problem_text`, which appears to parse the $PROBLEM statement from the control stream.

The code currently parses the $PROBLEM statement incorrectly. "LEM" is appended to this value in a subset of models. I believe this is due to the regular expression parser grabs anything after "$PROB" from the control stream. However, users can use either $PROB or $PROBLEM for this chunk of code.

**Comment by seth127** [comment]
This is actually in a problem in bbi. I created an issue there for it: https://github.com/metrumresearchgroup/babylon/issues/201
