### ISSUE TITLE
submit_model silently fails

### ISSUE THREAD

**Issue by callistosp** [metrumresearchgroup/rbabylon#35]
## Problem
Currently when you run `submit_model()` on a model which has already run (i.e. a results folder exists in your model directory), the model is not run. No warning is given that the model is not being submitted to run. The only way to get around this is to delete the results folder.

## Proposed solution:
 * Adding a `.overwrite` argument to `submit_model()` would be useful for this situation. This argument would default to `FALSE` to prevent people from accidentally overwriting results
 * A warning should be given when `submit_model(..., .overwrite=F)` is run, but the model will not be submitted due to a results folder already existing

**Comment by dpastoor** [comment]
this actually already exists, its one of the .bbi_args

**Comment by seth127** [comment]
Per our discussion in slack, should this move to the `babylon` board? @shairozan it sounds like the real issue is that `bbi` doesn't return a non-zero exit code when the submission fails (for instance, because there's already an output folder and the user did _not_ specify overwrite). Is that right @dpastoor ?

**Comment by shairozan** [comment]
This was already updated in RC2 earlier today. https://github.com/metrumresearchgroup/babylon/issues/143.

**Comment by shairozan** [comment]
```
INFO[0000] Successfully loaded default configuration from /data/home/darrellb/export/babylon.yaml
INFO[0000] Beginning Local Path
INFO[0000] expanding model pattern: 240/[001:009].mod
INFO[0000] A total of 9 models have completed the initial preparation phase
ERRO[0000] 9 errors were experienced during the run
ERRO[0000] Errors were experienced while running model 001. Details are The target directory, /data/home/darrellb/export/240/001 already exist, but we are configured not to overwrite. Invalid configuration / run state
ERRO[0000] Errors were experienced while running model 002. Details are The target directory, /data/home/darrellb/export/240/002 already exist, but we are configured not to overwrite. Invalid configuration / run state
ERRO[0000] Errors were experienced while running model 003. Details are The target directory, /data/home/darrellb/export/240/003 already exist, but we are configured not to overwrite. Invalid configuration / run state
ERRO[0000] Errors were experienced while running model 004. Details are The target directory, /data/home/darrellb/export/240/004 already exist, but we are configured not to overwrite. Invalid configuration / run state
ERRO[0000] Errors were experienced while running model 005. Details are The target directory, /data/home/darrellb/export/240/005 already exist, but we are configured not to overwrite. Invalid configuration / run state
ERRO[0000] Errors were experienced while running model 006. Details are The target directory, /data/home/darrellb/export/240/006 already exist, but we are configured not to overwrite. Invalid configuration / run state
ERRO[0000] Errors were experienced while running model 007. Details are The target directory, /data/home/darrellb/export/240/007 already exist, but we are configured not to overwrite. Invalid configuration / run state
ERRO[0000] Errors were experienced while running model 008. Details are The target directory, /data/home/darrellb/export/240/008 already exist, but we are configured not to overwrite. Invalid configuration / run state
ERRO[0000] Errors were experienced while running model 009. Details are The target directory, /data/home/darrellb/export/240/009 already exist, but we are configured not to overwrite. Invalid configuration / run state
9 models completed in 10.268978ms

1
```

We can show that now after the overwrite fails because the directory exists the exit code from babylon is the 1 listed here.

**Comment by seth127** [comment]
This issue was fixed a long time ago and somehow never got closed. I just verified this bug no longer exists (see screenshot). 

<img width="959" alt="Screen Shot 2020-11-03 at 4 24 49 PM" src="https://user-images.githubusercontent.com/7806083/98042206-3517ad00-1df1-11eb-9c73-88bc480cb778.png">
