### ISSUE TITLE
Copying models in typical workflow

### ISSUE THREAD

**Issue by callistosp** [metrumresearchgroup/rbabylon#37]
# Summary

## Problem

Currently the `copy_model_from` function will overwrite existing model and yaml files when it is called. This could potentially be an issue for reproducibility; e.g. if the analysis script is accidentally sourced, all models will be overwritten.

```
mod102 <- copy_model_from(file.path(MODEL_DIR, "101.yaml"),
                          file.path(MODEL_DIR, "102.yaml"), 
                          .description="two-compartment IIV(CL)")
```

In this case, `102.ctl` and `102.yaml` will both be overwritten with a copy of 101 every time this code is run.

## Solution

Existing files will *not* be overwritten by default. There should be an argument exposed to let users choose to overwrite an existing file if they want to.

## Tests
- tests/testthat/test-workflow.R
  - copy_from_model .overwrite_model_file=TRUE works
  - copy_from_model .overwrite_model_file=FALSE works

**Comment by dpastoor** [comment]
agree, lets add an overwrite option that defaults to false

**Comment by seth127** [comment]
@callistosp wrote in the original:
> It is unclear how the `.description` argument should be treated in the case of existing files. Potential edge case: `.description` matches `$PROBLEM` in the `102.ctl` file, but not `.description` in `102.yaml`.

Right now, the existing file isn't touched if `.overwrite_model_file=FALSE`. We can change that if want, but that's how I have it now.

**Comment by seth127** [comment]
PR #39 merged.
