### ISSUE TITLE
vignette link in README not currently working

### ISSUE THREAD

**Issue by andersone1** [metrumresearchgroup/rbabylon#49]
The link at the bottom of the README page links to the below page, which cannot be found:

http://metrumresearchgroup.github.io/rbabylon/

**Comment by seth127** [comment]
This is related to this PR that's languishing.
https://github.com/metrumresearchgroup/rbabylon/pull/46
Waiting on approval from @dpastoor to merge that and hopefully it fixes the issue.

**Comment by dpastoor** [comment]
This is fixed and merged, but only temporarily as is. We want to move to not using the docs subfolder and using a separate gh-pages branch to host. We can refactor that later This should not impact the overall link, just what lives in the master branch

**Comment by dpastoor** [comment]
#
