### ISSUE TITLE
reminder to unset gfortran env for 74

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/rbabylon#5]
per discussion 

https://www.mail-archive.com/nmusers@globomaxnm.com/msg06885.html

**Comment by shairozan** [comment]
Since R isn't actually performing the execution, babylon is, it would be worth testing at least, but my gut tells me it shouldn't be an issue.

**Comment by dpastoor** [comment]
This (was) an issue, and I believe did occur shelling out to bbi. That said, I believe this was just fixed in nonmem itself, per the conversation though now that I read carefully

> Users may call
Sys.unsetenv("GFORTRAN_STDOUT_UNIT")
at the beginning of an R session, as recommended by Tarj Sohata, or you can use 
a modified nmfe74.bat file located at:
https://nonmem.iconplc.com/nonmem741/extra/run

Usually when the modified bat files are done, those changes get incorporated into new versions of nonmem, so 744 shouldn't have that issue. We can close this now and re-evaluate if we notice issues if/when we get to windows compat testing
