### ISSUE TITLE
Estimate of Sigma (2,1) is displayed as 0 in model when it shouldn't be displayed

### ISSUE THREAD

**Issue by adamlafontaine** [metrumresearchgroup/rbabylon#62]
In a model where the $SIGMA starting values were not specified as a block, displaying the the parameter estimates with the following command resulted in the table below. After talking with Matt and @callistosp the inclusion of SIGMA(2,1) is not the preferred behavior. 

```text
model_summary(mod104) %>%
  param_estimates()
```

names| estimate|stderr |fixed
-------|------|------|------
OMEGA(3,3) | 0.1693070 | 1.97401e-02 | 0 |  
SIGMA(1,1) | 0.0397749 | 1.25788e-03 | 0 |  
SIGMA(2,1) | 0.0000000 | 1.00000e+10 | 1 |  
SIGMA(2,2) | 0.8410060 | 2.87706e+00 | 0 |

In the .ctl file the starting values for $SIGMA were not specified as a block.

$SIGMA
0.05     ; 1 pro error
0.05     ; 2 add error

## .lst file output

```text
FINAL PARAMETER ESTIMATE

 SIGMA - CORR MATRIX FOR RANDOM EFFECTS - EPSILONS  ***


         EPS1      EPS2     
 
 EPS1
+        1.99E-01
 
 EPS2
+        0.00E+00  9.17E-01

STANDARD ERROR OF ESTIMATE

SIGMA - CORR MATRIX FOR RANDOM EFFECTS - EPSILONS  ***


         EPS1      EPS2     
 
 EPS1
+        3.15E-03
 
 EPS2
+       .........  1.57E+00
```

**Comment by seth127** [comment]
@adamlafontaine can you run `bbi nonmem summary [ctl file path] --json` on the command line and paste in the output (or ideally just this parameter part of the output if you can easily extract it)?

If this is in that json that comes from bbi too then this should be an issue in https://github.com/metrumresearchgroup/babylon not here. I think that's probably the case, but I'm not sure.

**Comment by adamlafontaine** [comment]
It looks like it is in the json so I will create an issue for babylon then. 

        "parameters_data": [
                {
                        "method": "TABLE NO.     1: First Order Conditional Estimation with Interaction: Goal Function=MINIMUM VALUE OF OBJECTIVE FUNCTION: Problem=1 Subproblem=0 Superproblem1=0 Iteration1=0 Superproblem2=0 Iteration2=0",
                        "estimates": {
                                "theta": [
                                        0.432605,
                                        4.11838,
                                        1.11544,
                                        4.20827,
                                        1.2875
                                ],
                                "omega": [
                                        0.220155,
                                        0.0688803,
                                        0.0827208,
                                        0.13387,
                                        0.0735232,
                                        0.169307
                                ],
                                "sigma": [
                                        0.0397749,
                                        0,
                                        0.841006
                                ]
                        },
                        "std_err": {
                                "theta": [
                                        0.0630859,
                                        0.0276778,
                                        0.0328263,
                                        0.0191263,
                                        0.035593
                                ],
                                "omega": [
                                        0.0529672,
                                        0.0199708,
                                        0.00982676,
                                        0.0236165,
                                        0.0105625,
                                        0.0197401
                                ],
                                "sigma": [
                                        0.00125788,
                                        10000000000,
                                        2.87706
                                ]
                        },
                        "random_effect_sd": {
                                "omega": [
                                        0.469207,
                                        0.510415,
                                        0.287612,
                                        0.693395,
                                        0.621269,
                                        0.411469
                                ],
                                "sigma": [
                                        0.199436,
                                        0,
                                        0.917064
                                ]
                        },
                        "random_effect_sdse": {
                                "omega": [
                                        0.0564434,
                                        0.0975455,
                                        0.0170833,
                                        0.0689339,
                                        0.0524938,
                                        0.0239873
                                ],
                                "sigma": [
                                        0.00315357,
                                        10000000000,
                                        1.56862
                                ]
                        },
                        "fixed": {
                                "theta": [
                                        0,
                                        0,
                                        0,
                                        0,
                                        0
                                ],
                                "omega": [
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0
                                ],
                                "sigma": [
                                        0,
                                        1,
                                        0
                                ]
                        }
                }
        ],

**Comment by seth127** [comment]
I'm pretty sure we decided this is correct behavior and the user can filter these out if they want to. Also, with the new `param_labels()` function it will be easier to filter down to only the params that are actually specified in the control stream (aka not sigma(2,1)). See the vignette for an example:
https://metrumresearchgroup.github.io/rbabylon/articles/parameter-labels.html
