### ISSUE TITLE
feature idea: document commented records

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/rbabylon#70]
Just an idea that came out of our meeting today (@riggsmm and Adam L)

Something like: document records that get commented out at run time

- read in the data
- count by `C`
- dump to csv file

Or maybe check to see if data set has changed and document then?

**Comment by seth127** [comment]
@kylebaron @riggsmm we're cleaning up the rbabylon backlog. Is this still a relevant request or should we close it? I remember something about us not wanting to comment out records anymore for an unrelated reason.

**Comment by kylebaron** [comment]
I'll close this.  Thanks, @seth127
