### ISSUE TITLE
root model directory hardening

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/rbabylon#78]
additional testing/banging on using a single root, where the model path is relative to that root.

```
submit_model("subdir/model")
```

**Comment by seth127** [comment]
I'm not totally sure what this even entails at this point. Is there any clear acceptance criteria that we could define, or is this just playing around in some projects and making sure different configurations of paths work correctly?

Also, per the intro meeting we had with Curtis, it seems like @dpastoor has already done some of this ad-hoc.

Either way, let's try to define what should actually be done for this issue.

**Comment by seth127** [comment]
After conversation with @dpastoor we’re closing this. No real defined criteria and the “hardening” has been happening ad-hoc over the last week or two.
