### ISSUE TITLE
version constrain babylon within a particular rbabylon release

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/rbabylon#90]
# Summary

A user should be prevented from using a version of `bbi` that is too old to be compatible with the version of `rbabylon` they are using.

# Tests
- tests/testthat/test-use-bbi.R
  - bbi_version and bbi_current_version match
  - bbi_version returns nothing with fake bbi
- tests/testthat/test-rbabylon.R
  - check_bbi_exe() correctly errors or finds paths
  - check_bbi_exe() errors on too low version
  - check_bbi_version_constraint() works with semantic versioning

**Comment by seth127** [comment]
Full disclosure: I added the `check_bbi_version_constraint() works with semantic versioning` test after Devin mentioned that on the call this morning. But yes, it did already work.
