### ISSUE TITLE
custom file names

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/rbabylon#91]
# Summary
User should be able to specify a custom name for the `.ext` file when calling `model_summary()`. This should be passed in via `.bbi_args()`.

# Tests
- tests/testthat/test-summary.R
  - model_summary() works with custom .ext file
  - model_summary() works with no .cor file
  - model_summary() works with no .cov file
  - model_summary() works with no .ext file
  - model_summary() works with no .grd file
  - model_summary() works with no .shk file

**Comment by seth127** [comment]
Started looking at this, but it's really blocked by https://github.com/metrumresearchgroup/babylon/pull/171 merging and having a new release to test it on.

**Comment by seth127** [comment]
Also, @dpastoor from https://github.com/metrumresearchgroup/babylon/pull/171 it looks like only an `--ext-file` flag was added. Are there more to come, or is that it for now?
