### ISSUE TITLE
documentation triage around exported functions

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/rbabylon#92]
* unexport into rd the internal functions
* group functions into categories
    * example in dplyr: https://github.com/tidyverse/dplyr/blob/master/_pkgdown.yml#L17

**Comment by seth127** [comment]
Found this solution that seems fairly elegant. And it's from the Hadley book, so you know it's good.
https://stackoverflow.com/a/35846381/3743213

**Comment by seth127** [comment]
I'm gonna move this off of the milestone once the PR merges because this doesn't need to be part of validation.

**Comment by seth127** [comment]
Closing this and moving off milestone because there are no tests to validate.
